FROM python:3.9-slim

# Install dependencies
RUN pip install torch torchvision flask pillow requests --no-cache-dir

# Set working directory
WORKDIR /app

# Copy API code
COPY app/ /app/

# Copy test image
COPY istockphoto-1412238848-612x612.jpg /app/test.jpg

# Expose port
EXPOSE 5000

# Run the API
CMD ["python", "api.py"]