name: "yolov8"
platform: "pytorch_libtorch"
max_batch_size: 8
input [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [ 3, 640, 640 ]
  }
]
output [
  {
    name: "output0"
    data_type: TYPE_FP32
    dims: [ -1, -1 ]  # Variable size output
  }
]
instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]